### ISSUE TITLE
这些三元组是从哪些数据里面抽取出来的？

### ISSUE THREAD

**Issue by JianboTang** [ownthink/KnowledgeGraphData#16]

**Comment by ownthink** [comment]
各大百科

郑文裕


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jianbo Tang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 晚上8:04
收件人:&nbsp;"ownthink/KnowledgeGraphData"<KnowledgeGraphData@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ownthink/KnowledgeGraphData] 这些三元组是从哪些数据里面抽取出来的？ (#16)

**Comment by JianboTang** [comment]
可以公开不

**Comment by ownthink** [comment]
已经开放下载啦


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Jianbo Tang <notifications@github.com&gt;
发送时间: 2020年4月14日 20:23
收件人: ownthink/KnowledgeGraphData <KnowledgeGraphData@noreply.github.com&gt;
抄送: Yener <158760520@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ownthink/KnowledgeGraphData] 这些三元组是从哪些数据里面抽取出来的？ (#16)





 
可以公开不

**Comment by JianboTang** [comment]
> 已经开放下载啦 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Jianbo Tang <notifications@github.com&gt; 发送时间: 2020年4月14日 20:23 收件人: ownthink/KnowledgeGraphData <KnowledgeGraphData@noreply.github.com&gt; 抄送: Yener <158760520@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[ownthink/KnowledgeGraphData] 这些三元组是从哪些数据里面抽取出来的？ (#16) 可以公开不 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

额，我是指原始的数据能不能公开，就是你上面提到的各大百科

**Comment by ownthink** [comment]
这个我也没有，程序都是自动跑的，没对原始数据做存储。




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Jianbo Tang <notifications@github.com&gt;
发送时间: 2020年4月14日 20:51
收件人: ownthink/KnowledgeGraphData <KnowledgeGraphData@noreply.github.com&gt;
抄送: Yener <158760520@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ownthink/KnowledgeGraphData] 这些三元组是从哪些数据里面抽取出来的？ (#16)





  
已经开放下载啦 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Jianbo Tang <notifications@github.com&gt; 发送时间: 2020年4月14日 20:23 收件人: ownthink/KnowledgeGraphData <KnowledgeGraphData@noreply.github.com&gt; 抄送: Yener <158760520@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[ownthink/KnowledgeGraphData] 这些三元组是从哪些数据里面抽取出来的？ (#16) 可以公开不 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
额，我是指原始的数据能不能公开，就是你上面提到的各大百科

**Comment by LiangXD** [comment]
你好，请问下您这个三元组是怎么抽取的呢，比如我现在有一个文本，用什么手段可以将里面的实体-关系-实体，实体-属性-属性值抽取出来
