### ISSUE TITLE
数据有不少错误

### ISSUE THREAD

**Issue by yinruimin** [ownthink/KnowledgeGraphData#7]
我就搜了一些省份和地点，五台山的信息就有错误

**Comment by ownthink** [comment]
是否可以具体指出呢，我确认下

**Comment by yinruimin** [comment]
五台山的地理位置是山西忻州 你那里写的是陕西西安

发自我的iPhone

**Comment by ownthink** [comment]
&nbsp;这个你看错咯，你输入的是mention，系统判断到陕西的五台山了，所以地址是陕西西安，如果要查看山西五台山，需要输入：五台山[山西省忻州市五台山]


其实就是歧义关系，你可以根据这个接口查看，https://api.ownthink.com/kg/ambiguous?mention=五台山


你所看到的陕西五台山，如下图：





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yinruimin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月19日(星期六) 晚上10:10
收件人:&nbsp;"ownthink/KnowledgeGraphData"<KnowledgeGraphData@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/KnowledgeGraphData] 数据有不少错误 (#7)



五台山的地理位置是山西忻州 你那里写的是陕西西安
 
 发自我的iPhone
 
 &gt; 在 2019年10月19日，下午5:20，Yener <notifications@github.com&gt; 写道：
 &gt; 
 &gt; ﻿
 &gt; 是否可以具体指出呢，我确认下
 &gt; 
 &gt; —
 &gt; You are receiving this because you authored the thread.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yinruimin** [comment]
那你这个还是稍微有点缺陷，重名肯定会存在，检索之后，也应该关联词条之间平铺显示，而不是只取一条，更何况权重配的也不太合适，只是一些小建议，非常尊重你的技术成果

发自我的iPhone

**Comment by ownthink** [comment]
&nbsp;由于这个是为机器人设计的，所以只能取舍了，如果是为了给人进行可视化检索，你说的这个设计是非常正确的，但是我们是为了机器人设计的，所以也没办法只能利用权重消歧了，当然机器人会自动检索其需要的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yinruimin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月19日(星期六) 晚上10:42
收件人:&nbsp;"ownthink/KnowledgeGraphData"<KnowledgeGraphData@noreply.github.com&gt;;
抄送:&nbsp;"郑文裕"<158760520@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ownthink/KnowledgeGraphData] 数据有不少错误 (#7)



那你这个还是稍微有点缺陷，重名肯定会存在，检索之后，也应该关联词条之间平铺显示，而不是只取一条，更何况权重配的也不太合适，只是一些小建议，非常尊重你的技术成果
 
 发自我的iPhone
 
 &gt; 在 2019年10月19日，下午10:13，Yener <notifications@github.com&gt; 写道：
 &gt; 
 &gt; ﻿&amp;nbsp;这个你看错咯，你输入的是mention，系统判断到陕西的五台山了，所以地址是陕西西安，如果要查看山西五台山，需要输入：五台山[山西省忻州市五台山] 
 &gt; 
 &gt; 
 &gt; 其实就是歧义关系，你可以根据这个接口查看，https://api.ownthink.com/kg/ambiguous?mention=五台山 
 &gt; 
 &gt; 
 &gt; 你所看到的陕西五台山，如下图： 
 &gt; 
 &gt; 
 &gt; 
 &gt; 
 &gt; 
 &gt; ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 &gt; 发件人:&amp;nbsp;"yinruimin"<notifications@github.com&amp;gt;; 
 &gt; 发送时间:&amp;nbsp;2019年10月19日(星期六) 晚上10:10 
 &gt; 收件人:&amp;nbsp;"ownthink/KnowledgeGraphData"<KnowledgeGraphData@noreply.github.com&amp;gt;; 
 &gt; 抄送:&amp;nbsp;"郑文裕"<158760520@qq.com&amp;gt;;"State change"<state_change@noreply.github.com&amp;gt;; 
 &gt; 主题:&amp;nbsp;Re: [ownthink/KnowledgeGraphData] 数据有不少错误 (#7) 
 &gt; 
 &gt; 
 &gt; 
 &gt; 五台山的地理位置是山西忻州 你那里写的是陕西西安 
 &gt; 
 &gt; 发自我的iPhone 
 &gt; 
 &gt; &amp;gt; 在 2019年10月19日，下午5:20，Yener <notifications@github.com&amp;gt; 写道： 
 &gt; &amp;gt; 
 &gt; &amp;gt; ﻿ 
 &gt; &amp;gt; 是否可以具体指出呢，我确认下 
 &gt; &amp;gt; 
 &gt; &amp;gt; — 
 &gt; &amp;gt; You are receiving this because you authored the thread. 
 &gt; &amp;gt; Reply to this email directly, view it on GitHub, or unsubscribe. 
 &gt; 
 &gt; — 
 &gt; You are receiving this because you modified the open/close state. 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; —
 &gt; You are receiving this because you authored the thread.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
